### ISSUE TITLE
Trying to install this on awesome window manager following instructions but it fails

### ISSUE THREAD

**Issue by RazorRanger** [stefano-m/awesome-pulseaudio_widget#12]
Trying to install this on awesome window manager following instructions but it fails when I run luarocks install pulseaudio_widget. This is the output of the install

Installing https://luarocks.org/pulseaudio_widget-0.6.1-1.src.rock
Missing dependencies for pulseaudio_widget 0.6.1-1:
   pulseaudio_dbus >= 0.12.0, < 0.13 (not installed)

pulseaudio_widget 0.6.1-1 depends on lua >= 5.2 (5.4-1 provided by VM)
pulseaudio_widget 0.6.1-1 depends on pulseaudio_dbus >= 0.12.0, < 0.13 (not installed)
Installing https://luarocks.org/pulseaudio_dbus-0.12.0-2.src.rock
Missing dependencies for pulseaudio_dbus 0.12.0-2:
   dbus_proxy >= 0.9.0, < 0.11 (not installed)

pulseaudio_dbus 0.12.0-2 depends on lua >= 5.1 (5.4-1 provided by VM)
pulseaudio_dbus 0.12.0-2 depends on dbus_proxy >= 0.9.0, < 0.11 (not installed)
Installing https://luarocks.org/dbus_proxy-0.10.3-2.src.rock
Missing dependencies for dbus_proxy 0.10.3-2:
   lgi >= 0.9.0, < 1 (not installed)

dbus_proxy 0.10.3-2 depends on lua >= 5.1 (5.4-1 provided by VM)
dbus_proxy 0.10.3-2 depends on lgi >= 0.9.0, < 1 (not installed)
Installing https://luarocks.org/lgi-0.9.2-1.src.rock

lgi 0.9.2-1 depends on lua >= 5.1 (5.4-1 provided by VM)
make -C lgi
make[1]: Entering directory '/tmp/luarocks_lgi-0.9.2-1-3Gy5KX/lgi/lgi'
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
touch .depcheck
gcc -fPIC  -O2 -fPIC -I/usr/include -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall -Wextra -O2 -g -c -o buffer.o buffer.c
gcc -fPIC  -O2 -fPIC -I/usr/include -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall -Wextra -O2 -g -c -o callable.o callable.c
callable.c: In function ‘closure_callback’:
callable.c:1237:13: error: too few arguments to function ‘lua_resume’
 1237 |       res = lua_resume (L, NULL, npos);
      |             ^~~~~~~~~~
In file included from lgi.h:11,
                 from callable.c:12:
/usr/include/lua.h:300:15: note: declared here
  300 | LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg,
      |               ^~~~~~~~~~
make[1]: *** [Makefile:63: callable.o] Error 1
make[1]: Leaving directory '/tmp/luarocks_lgi-0.9.2-1-3Gy5KX/lgi/lgi'
make: *** [Makefile:16: all] Error 2

Error: Failed installing dependency: https://luarocks.org/pulseaudio_dbus-0.12.0-2.src.rock - Failed installing dependency: https://luarocks.org/dbus_proxy-0.10.3-2.src.rock - Failed installing dependency: https://luarocks.org/lgi-0.9.2-1.src.rock - Build error: Failed building.

**Comment by stefano-m** [comment]
Hi there, thanks for giving this project a shot!

The error you see is due to a failure to install one of the widget's dependencies, namely lgi.

A better place to look for help would be at the lgi project: https://github.com/lgi-devs/lgi

It looks like the error is due with an issue between lgi and the Lua version you're using (5.4.1)

```
error: too few arguments to function ‘lua_resume’
```

I found a discussion about this at https://github.com/lgi-devs/lgi/issues/247

lgi should work with Lua 5.2 and 5.3 though.

I hope this helps, but there isn't anything else I can do about this unfortunately, so I'm going to close this issue.

Good luck!
